<?php

defined('MOODLE_INTERNAL') || die();

function xmldb_league_upgrade($oldversion) {
    global $DB;
    $dbman = $DB->get_manager();

    if ($oldversion < 2016051900) {
        // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.
    }

    return true;
}